DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS QUIZZES;
DROP TABLE IF EXISTS RESULTS;

CREATE TABLE STUDENTS
(
ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL
);

CREATE TABLE QUIZZES
(
ID INTEGER PRIMARY KEY NOT NULL,
SUBJECT VARCHAR,
NUM_QUESTIONS INTEGER,
QUIZ_DATE VARCHAR
);

CREATE TABLE RESULTS
(
STUDENT_ID INT NOT NULL,
QUIZ_ID INT NOT NULL,
SCORE INT NOT NULL
);

INSERT INTO STUDENTS VALUES(001, 'John', 'Smith');
INSERT INTO QUIZZES VALUES(001, 'Python Basics', 5, 'Feb. 5, 2015');
INSERT INTO RESULTS VALUES(001, 001, 85 )